services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
